language: java

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8

script:
  - mvn -P test clean test

after_success:
  - mvn -P coverage
    clean
    cobertura:cobertura
    coveralls:report
